#%RAML 1.0
title: GeoFind API
version: v1
baseUri: https://example.com/api
mediaType:  application/json
types:
  User:
    properties:
      name:
        type: string
        example: "Martin Laiz Gomez"
      username:
        type: string
        example: "martinlaizg"
      email:
        type: string
        example: "martinlaizg@gmail.com"
      password:
        type: string
        example: "MyPassWOrd123"
      bdate?:
        type: date-only
        example: "1999-01-23"

/users:
  description: Usuarios de la aplicacion
  get:
    description: Obtener todos los usuarios
    responses:
      200:
        description: No hay error
        body: 
          application/json:
            example: |
              {"message":" ok"}
              
  post:
    description: Crea un usuario
    body:
      type: User
    responses:
      201:
        description: Se ha creado el usuario correctamente
        body: 
          application/json:
            example: |
              {"message":" ok"}
              
  /{id}:
    put:
      description: Modifica un usuario
      body:
        type: User
      responses:
        201:
          description: Se ha creado el usuario correctamente
          body: 
            application/json:
              type: User