#%RAML 1.0 DataType

type: object
displayName: User
properties:
  email:
    type: string
    example: "martinlaizg@gmail.com"
  username:
    type: string
    example: "martinlaizg"
  password:
    type: string
    example: "MyPassWOrd123"
  name:
    type: string
    example: "Martin Laiz Gomez"
  bdate?:
    type: date-only
    example: "1999-01-23"
